### PR TITLE
What's New on CPAN for March 2024

### PR DESCRIPTION
**Pull request by matstar2**

### CODE REVIEW

**Comment by manwar** [comment]
@matstar2 thanks for keeping this alive.

**Review by oalders — APPROVED** [review]
This looks great! Thank you for adding the images and also for including author names in this latest iteration. Was there a change to the article generation script that we should include in a subsequent pull request?

If you could branch directly off this repo rather than your fork, I think we will get automatic article previews from render.com  Let me know if you don't have permissions to do that.

**Comment by matstar2** [comment]
Yes, I had to change the script to take into account PAUSE id's. I will add that to it's own commit on the next pull request.

Is this what you mean by "branch directly off this repo"?

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository

It says "You can only create a branch in a repository to which you have push access." As far as I know, I don't have that.

**Comment by oalders** [comment]
I just gave you write access to this repository. Let me know if that doesn't fix it?

**Pull request merged**
