### PR TITLE
It is started

### PR DESCRIPTION
**Pull request by jacoby**
Will get further this weekend. Just want to plant a PR "flag", just in case

### CODE REVIEW

**Comment by briandfoy** [comment]
Good start. Feel free to ping me when you're further along.

**Comment by jacoby** [comment]
Will do.

**Comment by briandfoy** [comment]
Merging because it's the end of October. Draft articles jut sit there anyway.

**Comment by jacoby** [comment]
Thanks for that, and I will happily participate in the revision process when we get to it, but they judge Hacktoberfest on PRs, not merges.

**Comment by Leont** [comment]
Not to be unappreciative of your efforts, but why are we doing this?

As a community we've been trying to move people away from CGI and especially CGI.pm. Even its own documentation mentions 

> CGI.pm is no longer considered good practice for developing web applications, including quick prototyping and small web scripts. There are far better, cleaner, quicker, easier, safer, more scalable, more extensible, more modern alternatives available at this point in time. These will be documented with [CGI::Alternatives](https://metacpan.org/pod/CGI::Alternatives).

This article looks like it comes 15 years too late. I can't think of a single reason where one would to actively choose CGI.pm over all of the many alternatives in 2018.

**Comment by dnmfarrell** [comment]
@Leont you're welcome to submit articles of the kind you think we do need. In the meantime we've identified this as a topic that's interesting to some folks, so we're writing it.

**Comment by karenetheridge** [comment]
A brief mention of how to query directly with DBI is fine, but if any employee of mine was writing production perl code directly against DBI, I would sternly tell them to go and read the documentation for DBIx::Class.

This is directly analagous to "we don't roll our own object constructors anymore; we use Moo or Class::Tiny or Moose or Mojo::Base etc".

**Comment by Grinnz** [comment]
In my opinion, writing an article on how to use DBI in 2018 is fine, but it must use DBIx::Connector/DBIx::Handler so as to not perpetuate non-fork-safe non-reconnecting DBI usage or usage without RaiseError set, and it should not show ->prepare and ->execute unless absolutely necessary (such as showing how to bind a parameter as SQL_BLOB). Unnecessary statement handles and lack of RaiseError are the biggest causes of DBI messes.

**Comment by Grinnz** [comment]
Additionally in regards to DBI+MySQL specifically: It is not a good idea to recommend DBD::mysql for new code. It has [fundamentally broken unicode handling](https://github.com/perl5-dbi/DBD-mysql/issues/197) for which the fix has been reverted and is unlikely to be reapplied for backcompat reasons. Thus, DBD::MariaDB should be used for all new code.

**Comment by jacoby** [comment]
Poke!

**Comment by briandfoy** [comment]
Grinnz makes some excellent points that you should incorporate into your article. :)

**Comment by dnmfarrell** [comment]
> It should not show ->prepare and ->execute unless absolutely necessary (such as showing how to bind a parameter as SQL_BLOB)...

@Grinnz can you select data without using `prepare` and `execute`?

**Comment by Grinnz** [comment]
Yes - with the selectrow_* and selectall_* family of methods.

**Comment by dnmfarrell** [comment]
Gotcha, I thought they were just convenience methods, is that why you were recommending them, or are they safer too?

**Comment by Grinnz** [comment]
There's no functional difference between using them and expanding out to a correctly written ->prepare/->execute/->fetch* loop, but the latter is harder to read, harder to debug, and more prone to not being correctly written.

**Comment by dnmfarrell** [comment]
Ok, thanks for the explanation.

**Comment by Grinnz** [comment]
It is probably still worth mentioning the prepare/execute/fetch format for when you will reuse a statement handle hundreds of times, but a) it's not as much of a benefit as you'd think in most cases because most DBD drivers do not use server-side prepare, and b) people (myself included, once upon a time) tend to take this as an excuse to make their code harder to read for the much more common case where a query is only run once.

**Comment by oalders** [comment]
@jacoby did you want to finish this one? It's still in `draft`.

**Pull request merged**
