### PR TITLE
remove jquery and code that uses it

### PR DESCRIPTION
**Pull request by matstar2**
Result of investigating #346. Turns out latest articles are generated elsewhere.

### CODE REVIEW

**Comment by oalders** [comment]
It would be great to remove jQuery, but it looks like our Bootstrap relies on it. The Chrome developer console shows:

```
Error: Bootstrap's JavaScript requires jQuery
    at bootstrap.min.js:6:37
(anonymous) @ bootstrap.min.js
```

I'm also seeing things like:

```
<script>
$(document).ready(function(){
   $('#latest-articles').load("/latest_articles/");
});
</script>
```

I think we would need to see if those are still required as well.

**Comment by matstar2** [comment]
That bit of js is the only thing using the jquery. Apart from bootstrap, that is.

**Comment by oalders** [comment]
It's entirely possible that we're not taking advantage of Bootstrap features which require jQuery.

**Comment by matstar2** [comment]
...and that js was replaced with other js elsewhere.

**Comment by oalders** [comment]
Right, so I think we might need to rebuild the Bootstrap files before we can drop jQuery entirely. We may be able to do that without bumping the Bootstrap version.

**Comment by paultcochrane** [comment]
> I'm also seeing things like:
> 
> ```
> <script>
> $(document).ready(function(){
>    $('#latest-articles').load("/latest_articles/");
> });
> </script>
> ```

It looks like jQuery code like this has been removed (see 2e53d40ca6f432d9f49fa980752226c17ae9611a).

It's possible to use Bootstrap without the JavaScript (and hence jQuery). Since some of the layout is done with Bootstrap's CSS, I'd recommend leaving the Bootstrap CSS as it is, however I'm pretty sure jQuery and Bootstrap's JavaScript can be removed without problem.

**Pull request closed without merging**
